# Development environmet

services:
  web:
    container_name: drinklog-dev
    build:
      context: .
      target: builder
    command: >
      sh -c "/app/docker-entrypoint.sh && python3 manage.py flush --noinput && python3 manage.py migrate && python3 manage.py createsuperuser --noinput && sleep infinity"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    volumes:
      - ./app:/app

  db:
    container_name: drinklog-db
    image: postgres:15
    volumes:
      - db-dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  db-dev:
