# Development environmet

services:
  web:
    container_name: drinklog-web-dev
    build:
      context: .
      target: builder
    command: >
      sh -c "/app/docker-entrypoint.sh"
    ports:
      - "8000:8000"
      - "1234:1234"
    env_file:
      - ./.env.dev
    volumes:
      - ./app:/app

  db:
    container_name: drinklog-db-dev
    image: postgres:15
    volumes:
      - db-dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  db-dev:
