services:
  web:
    container_name: drinklog-dev
    build:
      context: .
      target: builder
    entrypoint: ["sleep", "infinity"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
