# Production environment

services:
  web:
    container_name: drinklog-web
    build:
      context: .
      target: production
    command: gunicorn drinklog.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod

  db:
    container_name: drinklog-db
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  db:
