# Production environment

services:
  app:
    container_name: drinklog-app
    build:
      context: .
      target: production
    restart: unless-stopped
    command: gunicorn drinklog.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - frontend
      - db

  db:
    container_name: drinklog-db
    image: postgres:15
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  db:
